### ISSUE TITLE
Unable to download data？

### ISSUE THREAD

**Issue by nicolechenbiiiii** [DistriNet/DLTC#1]
Hi!

This is a very interesting project and a great paper, thanks for this work!

We would like to run your code as close as possible to your evaluations. Unfortunately, we cannot reach your data right now, it would thus be very helpful for us if you could update the newest websit of your data.

We would greatly appreciate that, thanks in advance.

**Comment by verarim** [comment]
Hi! Thank you for reaching out. We have updated the data link, so you can download the research data again. The link will expire on January 1, 2023. The [website](https://distrinet.cs.kuleuven.be/software/tor-tc-dl/) is online, but the 1-million traces dataset is not yet available for download. We're currently working on a permanent solution for publishing the whole dataset, stay tuned.

In the meantime, for being informed when the full dataset is available, including the PCAPs, you can fill in [this form](https://docs.google.com/forms/d/e/1FAIpQLSckzKyh9lRfpEs0W6PDkEXvj3pDv1bJ37lE7FL98ybtjSHs9w/viewform), and we will contact you.
